
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: backup
  name: mongodb-filesystem-backup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - bash
            - -c
            - mkdir -p /backupstorage/mongodb/ 2>/dev/null && rm -rfv /backupstorage/mongodb/* 2> /dev/null  && mongodump -h mongodb -u admin -p $DATABASE_ADMIN_PASSWORD  --authenticationDatabase admin -o /backupstorage/mongodb/ && exit 0;
            env:
            - name: DATABASE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-admin-password
                  name: mongodb
            image: mongodb:3.4
            imagePullPolicy: Always
            name: mongodb-filesystem-backup
            resources:
              limits:
                cpu: 500m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backupstorage
              name: backupstorage               
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: backupstorage
            persistentVolumeClaim:
              claimName: backupstorage
          
  schedule: 00 23 * * *
  successfulJobsHistoryLimit: 1
  suspend: false
